### ISSUE TITLE
Specialized Platforms

### ISSUE THREAD

**Issue by fkarg** [SoPra18-07/Singularity#11]
Create objects for specialized platforms according to architecture

When finished, the following platform-types should exist:
- [x] #9 Blank Platform
- [x] #74 Mine
- [x] #73 Quarry
- [x] #82 Factory
- [x] #75 Junkyard
- [ ] #83 Storage
- [x] #84 Command Center
- [ ] #85 Packaging
- [x] #72 Well
- [x] #76 Energy Facility
- [ ] #86 Armory
- [x] #87 Barracks
- [x] #88 Laser Defense
- [x] #89 Kinetic Defense

requires #9, requires #72, requires #73, requires #74, requires #75, requires #76, requires #82, requires #83, requires #84, requires #85, requires #86, requires #87, requires #88, requires #89

**Comment by yvan674** [comment]
The platforms have been divided by type as follows:

#### Resource extraction (Outputs resource):
- Mine
- Quarry
- Well

#### Resource processing (Consumes resource, outputs resource):
- Packaging
- Factory
- Storage

#### Resource consumption (Consumes resource):
- Energy
- Junkyard

#### Unit Management (Produces and controls units):
- Barracks
- Command Center

#### Defense:
- Laser Defense
- Kinetic Defense
- Armory

**Comment by fkarg** [comment]
requires #72
requires #73
requires #74
requires #75
requires #76
