### ISSUE TITLE
Add the ReSharper to Travis

### ISSUE THREAD

**Issue by fkarg** [SoPra18-07/Singularity#25]
extend the .travis.yml so that before building, the ReSharper is being run with the SoPra configuration, and the build fails if the ReSharper finds errors.

**Comment by jonmcoe** [comment]
did the resharper / `inspectcode.exe` shown here ever work for travis? https://github.com/SoPra18-07/Singularity/commit/2d8afd79e792e9d70e3757ca6fd1ede89cc73a08
