### ISSUE TITLE
Weird resource behavior

### ISSUE THREAD

**Issue by Ativelox** [SoPra18-07/Singularity#255]
**Describe the bug**
The resources on platforms sometimes jump directly to units on their way to said platform

**To Reproduce**
Start up the game and hope units get distributed in such a way that the bug happens (...)

**Expected behavior**
The resources should wait for the unit to arrive at its platform and then get picked up

**Gif that shows the issue**
![bug](https://user-images.githubusercontent.com/22010681/42063402-6dac0348-7b6c-11e8-90f9-7afb13354637.gif)

**Comment by Confectio** [comment]
I honestly have no idea why this happens. I think felix had an idea but we forgot to talk about it
