### ISSUE TITLE
Make Issues out of the TODOS in Code

### ISSUE THREAD

**Issue by fkarg** [SoPra18-07/Singularity#278]

**Comment by Ativelox** [comment]
i think we don't need to. Its really just overhead we don't need right now. But if you are convinced this will be way better than we should get back to it on the meeting

**Comment by fkarg** [comment]
Sorry I haven't read that up until now (having finished it) - tbh it was a quite good way to get a rough state of where we are right now and since basically all of it still needs to be done, it's also better to have it written down here as well .. or at least I think so.
