### ISSUE TITLE
Make Path sorted

### ISSUE THREAD

**Issue by fkarg** [SoPra18-07/Singularity#318]
maybe make sure the nodes are sorted when GetVectorPath() or GetNodePath() gets called, because right now we actually rely on whoever creates this to add the path in a sorted fashion

SortedPath.cs

**Comment by Ativelox** [comment]
actually did that at some point, probably got overriden

**Comment by fkarg** [comment]
so could you look into it if it's like that still or if the Todo is just redundant? @Ativelox

**Comment by Ativelox** [comment]
It’s still like that
