### ISSUE TITLE
Do not Request Units

### ISSUE THREAD

**Issue by Confectio** [SoPra18-07/Singularity#350]
Line 118 in ProduceResource. Are there maybe other changes to be done, too?

**Comment by fkarg** [comment]
How does the PlatformAction tell the DistributionManager that it's 'unpaused' and wants units again then? (it's commented currently)

**Comment by Confectio** [comment]
I guess we unregister the platform with bool inactivate = true, to handle the platform as if it was inactivated. Since we got no multiple producing or defending platforms it should be fine. The other platformactions do not request units anway.

**Comment by fkarg** [comment]
yea but is that functionality there already?
