### ISSUE TITLE
Click on placed Barracks crashes the game

### ISSUE THREAD

**Issue by Ativelox** [SoPra18-07/Singularity#406]
the line where it says:

`foreach (var resource in platformAction.GetRequiredResources())`

throws an exception due to `GetRequiredResources()` being null. I suppose its an underlying issue not having to do with the UI explicitly, so I will assign felix and anselm, because they probably know the most about it.

**Comment by fkarg** [comment]
Yes I'll fix that soon. Should be the same with DefensePlatform(s) currently.
