### ISSUE TITLE
Implement the Mine (specialized Platform)

### ISSUE THREAD

**Issue by fkarg** [SoPra18-07/Singularity#74]
Communicating with the resource map to look for Mine-Based Resources underneath and getting them up. - no wait that's for the PlatformAction to handle .... so it's actually just a blank platform with a special texture?

**Comment by Confectio** [comment]
If its correct, that the PlatformAction handles the whole procces/action itself, then yes Id say thats it. Should we implement that a mine can only be built on resources or can the player also build a mine on a place whithout resources? Id suggest the last.
